[package]
name = "multra"
version = "1.0.2"
description = "An async parser for `multipart/form-data` content-type in Rust."
homepage = "https://github.com/salvo-rs/multra"
repository = "https://github.com/salvo-rs/multra"
keywords = ["multipart", "multipart-formdata", "multipart-uploads", "async", "formdata"]
categories = ["asynchronous", "web-programming"]
authors = ["Rousan Ali <hello@rousan.io>", "Chris Young <chris@sonc.ai>"]
readme = "README.md"
license = "MIT"
edition = "2024"
rust-version = "1.94"

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
features = ["all"]

[features]
default = []
all = ["json"]
json = ["serde", "serde_json"]
tokio-io = ["tokio", "tokio-util"]
log = ["dep:log"]

[dependencies]
bytes = "1.12.1"
futures-util = { version = "0.3.32", default-features = false }
memchr = "2.8.3"
http = "1.4.2"
httparse = "1.10.1"
mime = "0.3.17"
encoding_rs = "0.8.35"

log = { version = "0.4.33", optional = true }
serde = { version = "1.0.228", optional = true }
serde_json = { version = "1.0.150", optional = true }
tokio = { version = "1.52.3", features = [], optional = true }
tokio-util = { version = "0.7.18", features = ["io"], optional = true }

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
hyper = { version = "1.10.1", features = ["server", "http1"] }
http-body-util = "0.1.4"
hyper-util = { version = "0.1.20", features = ["full"] }

[[example]]
name = "parse_async_read"
path = "examples/parse_async_read.rs"
required-features = ["tokio-io"]
