name: Typos

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check typos
        uses: crate-ci/typos@24c5854966d17070a3b25e2c2dfc63ec5bc94cf4 # v1.40.0
